# Generated by Django 5.1.1 on 2024-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_returnrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersub',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
