# Generated by Django 5.0.6 on 2024-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, unique=True)),
                ('category_description', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
