# Generated by Django 5.0.6 on 2024-07-18 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
    ]
