# Generated by Django 5.0.6 on 2024-07-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
